### PR TITLE
fix NETSTANDARD2_1 CS0121

### PR DESCRIPTION
**Pull request by AigioL**
Fix extension method conflict when TFM is netstandard 2.1

netstandard 2.1 is on for xamarin (Android / iOS)

https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskasyncenumerableextensions.configureawait?view=netstandard-2.1

F8CYXCC~~$L0M{4_7@H07}F

### CODE REVIEW

**Comment by JustArchi** [comment]
> netstandard 2.1 is on for xamarin (Android / iOS)

netstandard2.1 should have most if not all of features that Madness implements, why do you include it in your project? What features are you missing that Madness provides?

**Comment by AigioL** [comment]
netstandard 2.1 does have most implementations, but it still lacks some new APIs for net6.0. I recently changed the ASF project TFM to netstandard 2.1 to run on Android

If madness supports netstandard 2.1, this part does not need to be modified
https://github.com/SteamTools-Team/ArchiSteamFarm/commit/4a8ffa7cd71f8eac8c5451b9608167093aa99808#diff-9b6528a0b3e69c82874813266f5a6528426c661c7f2a866f5fba53a5d0f60266R119-R123

**Comment by JustArchi** [comment]
I see, thanks.

However, if we want to provide Madness for netstandard2.1 then more fixes are required.

@AigioL can you see if you can provide your android/xamarin/ios/other targets with https://github.com/JustArchiNET/Madness/tree/netstandard2.1 ? I think I covered everything required for it to work, but I'd appreciate if you let me know if that works.

**Comment by JustArchi** [comment]
All changes here: https://github.com/JustArchiNET/Madness/compare/netstandard2.1

**Comment by AigioL** [comment]
Yes, it works. Can you release the new package right away?

**Comment by JustArchi** [comment]
Sure, thanks for testing. I'll close this PR then and merge my branch into main + schedule a release right away :slightly_smiling_face:.

BTW, you might be interested in making use of Madness also for the rest of your project - as you can see, I added proxies/implementations for quite a lot of needed functionalities, so you can save yourself some work, or even send PRs if you miss something.

**Pull request closed without merging**
