### PR TITLE
fix RuntimeMadness.ProcessStartTime on Xamarin.Android & net6.0-android

### PR DESCRIPTION
**Pull request by AigioL**
https://github.com/dotnet/runtime/issues/67583

```
android.runtime.JavaProxyThrowable: System.UnauthorizedAccessException: Access to the path '/proc/stat' is denied.
     ---> System.IO.IOException: Permission denied
       --- End of inner exception stack trace ---
        at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
        at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
        at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
        at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
        at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
        at System.IO.Strategies.UnixFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
        at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
        at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
        at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
        at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
        at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
        at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
        at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
        at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
        at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
        at System.IO.File.InternalReadAllText(String path, Encoding encoding)
        at System.IO.File.ReadAllText(String path)
        at System.Diagnostics.Process.get_BootTime()
        at System.Diagnostics.Process.BootTimeToDateTime(TimeSpan timespanAfterBoot)
        at System.Diagnostics.Process.get_StartTimeCore()
        at System.Diagnostics.Process.get_StartTime()
```

### CODE REVIEW

**Comment by JustArchi** [comment]
Thanks for report and PR.

You removed the `IsRunningOnMono` condition, and that one is important as Mono wrongly reports process start time and can't use it even if the exception doesn't throw.

I've addressed your problem in https://github.com/JustArchiNET/Madness/commit/5a39aa3511a7a02113d1e2508b0e38e3980d8663 - please feel free to check if it works the way you would've expected, and if yes I'll be happy to make a patch release with those changes :slightly_smiling_face:

**Comment by AigioL** [comment]
I think your commit has fixed the problem on net6-android, I just tried it on Xamarin.Android 12 and it does take about 16 hours longer than the correct time, but I don't quite understand how this SavedProcessStartTime field works, if this static class is not called he will will not be initialized, so this value may be larger than the correct value, I looked at the source code used in ASF, if there is no instruction STATS nor open WebUI, it will not be called, it seems to be initialized in Init due to IsRunningOnMono call, in this scenario can indeed be close to the correct value, so is this the case? Or is there some other reason?

I don't currently reference this library on net6.0-android because most of the extensions are not needed, except that asp.net core 6 is currently unavailable and using 2.2 requires the ConfigureWebHostDefaults extension.

Translated with www.DeepL.com/Translator (free version)

**Comment by JustArchi** [comment]
Static fields get compiled in when you reference to the class for the first time. So until your first call to `ProcessStartTime`, `IsRunningOnMono` or other stuff in this class, it won't get initialized. ASF calls `IsRunningOnMono` as part of its init, so the field is initialized very early and the difference is in seconds at most.

If you don't "naturally" make use of this class during initialization of your app, you might need to artificially make use of it, like doing `var _ = RuntimeMadness.ProcessStartTime` in your `Main()` just to record it for the first time.

Yes, this is why process start time is preferred, but I wanted to fix it also for netf variant of ASF, where Mono doesn't report the correct time from the process, and in this case I prefer to use a fallback. This isn't any golden solution to the problem, this whole library isn't, but it gets the job done when needed in usually a decent enough way.

I'll release a new version with this fix in, thanks for raising my attention to the exception.

**Comment by JustArchi** [comment]
You can call this in your `Main()` - https://github.com/JustArchiNET/Madness/commit/c371e1b5561ae2c3769921c8cac221b872866b17

**Pull request closed without merging**
